"""
Module with tools for use with vizconnect
"""

import os

import viz
import vizconnect
import vizinput


def findVizconnectConfigs(dir, listFullPath=True):
	"""find all the config files in a directory"""
	configs = []
	for filename in os.listdir(dir):
		fullPath = os.path.join(dir, filename)
		if (fullPath.endswith('.py')
				and isValidVizconnectFile(fullPath)):
			if listFullPath:
				configs.append(fullPath)
			else:
				configs.append(filename)
	return configs


def isValidVizconnectFile(filename):
	"""Checks if the vizconnect file is valid.
	@return bool
	"""
	try:
		with open(filename, 'r') as tempFile:
			text = tempFile.read()
			headerText = 'This module was generated by Vizconnect.' 
			if headerText in text:
				return True
	except IOError:
		pass
	return False


def chooseVizconnectConfig(configs):
	"""Select a config from a list of configs"""
	choice = vizinput.choose('Select a Vizconnect Configuration', configs)
	return configs[choice]

